### ISSUE TITLE
Question: How will data on saturn nodes be indexed?

### ISSUE THREAD

**Issue by pyropy** [filecoin-project/saturn-l2#23]
How will data on saturn nodes be indexed, could the [index provdier](https://github.com/filecoin-project/index-provider) be re-used somehow?

**Comment by aarshkshah1992** [comment]
@pyropy  

- For the MVP, an L2 node will be connected to all L1s in it's region. The set of L2s an L1 is connected to is called the L1s Swarm.
- L1 nodes will use consistent hashing to escape to the "X Closest" L2s in it's Swarm to retrieved a key K. 
- So, we don't really need to index content  on Saturn nodes.
