### ISSUE TITLE
 L2 nodes should persist `K` in their cache only if they see two requests for `K` in a specific time period

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/saturn-l2#3]
See the `Cache-on-second-hit rule` section in Section 4.2 of this [Akamai paper](https://www.akamai.com/site/en/documents/research-paper/algorithmic-nuggets-in-content-delivery-technical-publication.pdf).

Most content is only ever requested once(~75% as per the paper). If some content is popular, it will be accessed atleast twice and persisting only such content in the cache improves the cache hit ratio and reduces disk IO/cache-churn on the nodes.

**Comment by DiegoRBaquero** [comment]
Not possible for L1s, nginx doesn't support it

**Comment by aarshkshah1992** [comment]
@DiegoRBaquero  

Sorry, which part isn't possible here ?

**Comment by DiegoRBaquero** [comment]
Correct

**Comment by aarshkshah1992** [comment]
@DiegoRBaquero  Edited the issue to do this for L2 nodes only.
